export enum IconsEnum {
  Home = "home",
  Frame = "frame",
  Note = "note",
  Briefcase = "briefcase",
  Messages = "messages",
  Print = "print",
  Download = "download",
  ArrowDownCircle = "arrowDownCircle",
  Point = "point",
  CircleArrow = "circleArrow",
  RightArrow = "rightArrow",
  Light = "light",
  Dark = "dark",
}
